INSERT INTO `mobile_phones`.`os` (`name`, `description`, `create_year`) VALUES ('iOS 12', 'Операційна система для мобільних пристроїів компанії Apple', 2018);
INSERT INTO `mobile_phones`.`os` (`name`, `description`, `create_year`) VALUES ('Android 8.1', 'Чергова версія операційної системи Android, що спростила роботу із ШІ', 2017);
INSERT INTO `mobile_phones`.`os` (`name`, `description`, `create_year`) VALUES ('Android 7.1', 'ОС отримала підтримку багатовіконності та апаратну підтримку AR', 2016);
INSERT INTO `mobile_phones`.`os` (`name`, `description`) VALUES ('iOS 11', 'ОС принесла новий дизайн, оновлений додаток  AppStore, LivePhotos та багато іншого.');

INSERT INTO `mobile_phones`.`features` (`name`, `usage`) VALUES ('NFC', 'Використовується для безконтактної оплати, а також роботи із іншими пристроями.');
INSERT INTO `mobile_phones`.`features` (`name`, `usage`) VALUES ('WiFi', 'Використовуєтсья для під\'єднання до мережі без використання кабелю');
INSERT INTO `mobile_phones`.`features` (`name`, `usage`) VALUES ('GPS', 'Найпоширеніша система визначення місцезнаходження.');
INSERT INTO `mobile_phones`.`features` (`name`, `usage`) VALUES ('GLONASS', 'Російський аналог GPS');
INSERT INTO `mobile_phones`.`features` (`name`, `usage`) VALUES ('3D Touch', 'Визанчає 3 ступені сили натискання на екран смартфону');

INSERT INTO `mobile_phones`.`creator` (`name`, `email`, `owner`, `country`) VALUES ('Apple', 'support@apple.com', 'Tim Cook', 'USA');
INSERT INTO `mobile_phones`.`creator` (`name`, `email`, `owner`, `country`) VALUES ('Samsung', 'support@samsung.com', 'Choi Gee-Sung', 'Південна Корея');
INSERT INTO `mobile_phones`.`creator` (`name`, `email`, `owner`, `country`) VALUES ('Huawei', 'support@huawei.net', 'Ren Zhengfei', 'Китай');
INSERT INTO `mobile_phones`.`creator` (`name`, `email`, `owner`, `country`) VALUES ('Xiaomi', 'support@mi.com', 'Lei Jun', 'Китай');
INSERT INTO `mobile_phones`.`creator` (`name`, `email`, `owner`, `country`) VALUES ('Honor', 'support@honor.xyz', 'Lei Jun', 'Китай');
INSERT INTO `mobile_phones`.`creator` (`name`, `email`, `owner`, `country`) VALUES ('OnePlus', 'support@op.net', 'Pete Lau', 'Китай');
INSERT INTO `mobile_phones`.`creator` (`name`, `email`, `owner`, `country`) VALUES ('OPPO', 'support@oppo.com', 'Duan Youngping', 'Китай');

INSERT INTO `mobile_phones`.`processor` (`name`, `frequency`, `count_of_cores`, `maker`) VALUES ('A12 Bionic', '2.5 GHz', '6', 'Apple');
INSERT INTO `mobile_phones`.`processor` (`name`, `frequency`, `count_of_cores`, `maker`) VALUES ('A11 Bionic', '2.4 GHz', '6', 'Apple');
INSERT INTO `mobile_phones`.`processor` (`name`, `frequency`, `count_of_cores`, `maker`) VALUES ('A10 Fusion', '2.38 GHz', '6', 'Apple');
INSERT INTO `mobile_phones`.`processor` (`name`, `frequency`, `count_of_cores`, `maker`) VALUES ('Snapdragon 845', '2.8 GHz', '8', 'Qualcomm');
INSERT INTO `mobile_phones`.`processor` (`name`, `frequency`, `count_of_cores`, `maker`) VALUES ('Exynos 9 Octa 9810', '2.9 GHz', '8', 'Samsung');
INSERT INTO `mobile_phones`.`processor` (`name`, `frequency`, `count_of_cores`, `maker`) VALUES ('Snapdragon 835', '2.45 GHz', '8', 'Qualcomm');
INSERT INTO `mobile_phones`.`processor` (`name`, `frequency`, `count_of_cores`, `maker`) VALUES ('Kirin 970', '2.36 GHz', '8', 'Honor');
INSERT INTO `mobile_phones`.`processor` (`name`, `frequency`, `count_of_cores`, `maker`) VALUES ('Snapdragon 660', '2.2 GHz', '8', 'Qualcomm');
INSERT INTO `mobile_phones`.`processor` (`name`, `frequency`, `count_of_cores`, `maker`) VALUES ('Kirin 710', '2.2 GHz', '8', 'Honor');

INSERT INTO `mobile_phones`.`shop` (`name`, `rating`, `website`) VALUES ('Rozetka', '4.5', 'https://rozetka.com.ua/');
INSERT INTO `mobile_phones`.`shop` (`name`, `rating`, `website`) VALUES ('ALLO', '4.7', 'https://allo.ua/');
INSERT INTO `mobile_phones`.`shop` (`name`, `rating`, `website`) VALUES ('Comfy', '4.6', 'https://comfy.ua/ua/');
INSERT INTO `mobile_phones`.`shop` (`name`, `rating`, `website`) VALUES ('MOYO', '3.9', 'https://www.moyo.ua');
INSERT INTO `mobile_phones`.`shop` (`name`, `rating`, `website`) VALUES ('Stylus', '3.5', 'https://stylus.ua');
INSERT INTO `mobile_phones`.`shop` (`name`, `rating`, `website`) VALUES ('Funduk.ua', '3.7', 'https://funduk.ua');

INSERT INTO `mobile_phones`.`phone` (`creator_id`, `model`, `processor_id`, `storage`, `RAM`, `resolution`, `screen_size`, `screen_type`, `os_id`) VALUES ('1', 'iPhone 7', '3', '128', '2', '1334x750', '4.7\"', 'Retina', '5');
INSERT INTO `mobile_phones`.`phone` (`creator_id`, `model`, `processor_id`, `storage`, `RAM`, `resolution`, `screen_size`, `screen_type`, `os_id`) VALUES ('1', 'iPhone 7 Plus', '3', '128', '3', '1920x1080', '5.5\"', 'Retina', '5');
INSERT INTO `mobile_phones`.`phone` (`creator_id`, `model`, `processor_id`, `storage`, `RAM`, `resolution`, `screen_size`, `screen_type`, `os_id`) VALUES ('2', 'Galaxy S9', '5', '64', '4', '2960x1440', '5.8\"', 'Super Amoled', '2');
INSERT INTO `mobile_phones`.`phone` (`creator_id`, `model`, `processor_id`, `storage`, `RAM`, `resolution`, `screen_size`, `screen_type`, `os_id`) VALUES ('4', 'Mi 8', '4', '64', '6', '2248×1080', '6.21\"', 'Super Amoled', '2');
INSERT INTO `mobile_phones`.`phone` (`creator_id`, `model`, `processor_id`, `storage`, `RAM`, `resolution`, `screen_size`, `screen_type`, `os_id`) VALUES ('4', 'Mi A2', '8', '64', '4', '2160x1080', '5.99\"', 'IPS', '2');
INSERT INTO `mobile_phones`.`phone` (`creator_id`, `model`, `processor_id`, `storage`, `RAM`, `resolution`, `screen_size`, `screen_type`, `os_id`) VALUES ('3', 'P Smart Plus', '9', '64', '4', '2340x1080', '6.3\"', 'IPS', '2');
INSERT INTO `mobile_phones`.`phone` (`creator_id`, `model`, `processor_id`, `storage`, `RAM`, `resolution`, `screen_size`, `screen_type`, `os_id`) VALUES ('5', '8X', '9', '64', '4', '2340x1080', '6.5\"', 'LTPS', '2');
INSERT INTO `mobile_phones`.`phone` (`creator_id`, `model`, `processor_id`, `storage`, `RAM`, `resolution`, `screen_size`, `screen_type`, `os_id`) VALUES ('5', 'Play', '7', '64', '4', '2340x1080', '6.3\"', 'IPS', '2');
INSERT INTO `mobile_phones`.`phone` (`creator_id`, `model`, `processor_id`, `storage`, `RAM`, `resolution`, `screen_size`, `screen_type`, `os_id`) VALUES ('3', 'P20 Pro', '7', '64', '4', '2240x1080', '6.1\"', 'OLED', '3');
INSERT INTO `mobile_phones`.`phone` (`creator_id`, `model`, `processor_id`, `storage`, `RAM`, `resolution`, `screen_size`, `screen_type`, `os_id`) VALUES ('1', 'iPhone X', '2', '64', '3', '2436x1125', '5.8\"', 'Super Retina (OLED)', '4');
INSERT INTO `mobile_phones`.`phone` (`creator_id`, `model`, `processor_id`, `storage`, `RAM`, `resolution`, `screen_size`, `screen_type`, `os_id`) VALUES ('1', 'iPhone XR', '1', '128', '4', '1792x828', '6.1\"', 'Retina', '1');
INSERT INTO `mobile_phones`.`phone` (`creator_id`, `model`, `processor_id`, `storage`, `RAM`, `resolution`, `screen_size`, `screen_type`, `os_id`) VALUES ('6', '6', '4', '64', '4', '2280x1080', '6.28\"', 'Amoled', '2');
INSERT INTO `mobile_phones`.`phone` (`creator_id`, `model`, `processor_id`, `storage`, `RAM`, `resolution`, `screen_size`, `screen_type`, `os_id`) VALUES ('7', 'Find X', '4', '256', '8', '2340x1080', '6.42\"', 'Amoled', '2');
INSERT INTO `mobile_phones`.`phone` (`creator_id`, `model`, `processor_id`, `storage`, `RAM`, `resolution`, `screen_size`, `screen_type`, `os_id`) VALUES ('2', 'Galaxy S8', '6', '64', '4', '2960x1440', '5.8\"', 'Super Amoled', '3');
INSERT INTO `mobile_phones`.`phone` (`creator_id`, `model`, `processor_id`, `storage`, `RAM`, `resolution`, `screen_size`, `screen_type`, `os_id`) VALUES ('2', 'Galaxy Note 9', '5', '128', '6', '2960x1440', '6.4\"', 'Super Amoled', '2');

INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('1', '1');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('1', '2');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('1', '3');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('1', '4');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('1', '5');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('2', '1');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('2', '2');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('2', '3');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('2', '4');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('2', '5');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('3', '1');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('3', '2');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('3', '3');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('3', '4');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('3', '6');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('4', '1');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('4', '2');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('4', '3');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('4', '4');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('5', '2');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('5', '3');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('5', '4');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('6', '2');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('6', '3');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('6', '4');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('7', '1');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('7', '2');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('7', '3');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('7', '4');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('8', '1');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('8', '2');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('8', '3');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('8', '4');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('9', '1');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('9', '2');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('9', '3');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('9', '4');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('9', '6');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('10', '1');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('10', '2');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('10', '3');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('10', '4');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('10', '5');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('10', '6');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('11', '1');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('11', '2');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('11', '3');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('11', '4');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('11', '6');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('12', '1');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('12', '2');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('12', '3');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('12', '4');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('12', '6');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('13', '1');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('13', '2');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('13', '3');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('13', '4');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('13', '6');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('14', '1');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('14', '2');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('14', '3');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('14', '4');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('15', '1');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('15', '2');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('15', '3');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('15', '4');
INSERT INTO `mobile_phones`.`phone_has_features` (`phone_id`, `features_id`) VALUES ('15', '6');

INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('1', '4', '20999', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('1', '2', '19999', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('1', '5', '17599', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('1', '1', '17809', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('1', '6', '20989', '40', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('1', '3', '19999', '0', '0');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('2', '1', '22250', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('2', '2', '23999', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('2', '3', '23499', '0', '0');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('2', '4', '25999', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('2', '5', '21499', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('2', '6', '23999', '40', '0');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('3', '1', '22999', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('3', '2', '22999', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('3', '3', '25999', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('3', '4', '22999', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('3', '5', '16999', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('3', '6', '23999', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('4', '1', '13999', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('4', '2', '13999', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('4', '5', '11399', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('4', '6', '11799', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('5', '1', '6999', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('5', '2', '6999', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('5', '3', '6999', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('5', '6', '6999', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('6', '1', '7799', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('6', '2', '7799', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('6', '3', '7799', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('6', '4', '7799', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('6', '5', '7499', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('6', '6', '7395', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('7', '2', '7699', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('7', '3', '7699', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('8', '2', '9999', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('8', '3', '9999', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('8', '4', '10599', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('9', '1', '24799', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('9', '2', '24799', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('9', '3', '24799', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('9', '4', '24799', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('9', '5', '20499', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('9', '6', '22499', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('10', '2', '31999', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('10', '3', '31999', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('10', '4', '31999', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('10', '5', '26999', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('10', '6', '35999', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('11', '2', '33999', '0', '0');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('11', '3', '33999', '0', '0');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('11', '4', '33999', '0', '0');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('11', '5', '29499', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('12', '2', '13999', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('12', '5', '12999', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('14', '1', '18499', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('14', '2', '18499', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('14', '3', '18499', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('14', '4', '18499', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('14', '5', '13499', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('14', '6', '19999', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('15', '1', '32999', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('15', '2', '32999', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('15', '3', '34999', '0', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('15', '5', '23999', '50', '1');
INSERT INTO `mobile_phones`.`shop_has_phone` (`phone_id`, `shop_id`, `price`, `shipping_cost`, `available`) VALUES ('15', '6', '34999', '50', '1');
